-- *** SAMPLE PUBLISHER ***
-- INSERT INTO PUBLISHER (PUBLISHER_ID,PUBLISHER_NAME,EMAIL_ADDRESS,IS_ENABLED,IS_ADMIN,MAX_BUSINESSES,MAX_SERVICES_PER_BUSINESS,MAX_BINDINGS_PER_SERVICE,MAX_TMODELS)
-- VALUES ('jdoe','John Doe','john.doe@apache.org','true','true',25,20,10,100);

