
package org.apache.juddi.samples;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorld", targetNamespace = "http://samples.juddi.apache.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorld {


    /**
     * 
     * @param text
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://samples.juddi.apache.org/", className = "org.apache.juddi.samples.SayHi")
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://samples.juddi.apache.org/", className = "org.apache.juddi.samples.SayHiResponse")
    public String sayHi(
        @WebParam(name = "text", targetNamespace = "")
        String text);

}
