//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Web.Services.WebServiceBindingAttribute(Name="Hello_Binding", Namespace="http://www.examples.com/wsdl/HelloService.wsdl", 
    Location="http://www.contoso.com/MyService.asmx?wsdl")]
public interface IHello_Binding {
    
    /// <remarks/>
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("sayHello", RequestNamespace="urn:examples:helloservice", ResponseNamespace="urn:examples:helloservice")]
    [return: System.Xml.Serialization.SoapElementAttribute("greeting")]
    string sayHello(string firstName);
}
