Apache jUDDI Client and GUI Guide
=================================
:doctype: book
:backend: docbook5
:docinfo: 

[dedication]
Dedication
----------
We'd like to dedicate this guide to Steve Viens and Andy Cutright who started this project back in 2003.

[preface]
Preface
-------
The jUDDI client framework facilitates interaction with any UDDI v3 compliant registry. In addition to providing a client framework for both Java and .NET, it also provides a self proclaimed Technical Compatilibity Test (TCK) Suite. The jUDDI community encourages collabration of other vendors on the TCK or on the client framework in general.

include::ClientGuideSimplePublishingUsingthejUDDIAPI.asciidoc[]

include::ClientGuidejUDDIClientConfigurationGuide.asciidoc[]

include::ClientGuideKeyFormatTemplates.asciidoc[]

include::ClientGuideUsingthejUDDIGUI.asciidoc[]

include::ClientGuideMappingWADLandWSDLtoUDDI.asciidoc[]

include::ClientGuideUsingUDDIAnnotationstoAutomateRegistration.asciidoc[]

include::ClientGuideUDDIv2Services.asciidoc[]

include::ClientGuideUDDIMigrationTool.asciidoc[]

include::ClientGuideUsingjUDDIRestServices.asciidoc[]

include::ClientGuidejUDDIClientforNET.asciidoc[]

include::ClientGuideTCKRunner.asciidoc[]

:numbered!:

////
/* commented out till we start using it */
[appendix]
Example Appendix
----------------
One or more optional appendixes go here at section level 1.

Appendix Sub-section
~~~~~~~~~~~~~~~~~~~
Sub-section body.


[bibliography]
Example Bibliography
--------------------
The bibliography list is a style of AsciiDoc bulleted list.

[bibliography]
.Books
- [[[walsh-muellner]]] Norman Walsh & Leonard Muellner.
'DocBook - The Definitive Guide'. O'Reilly & Associates. 1999.
ISBN 1-56592-580-7.

[bibliography]
.Articles
- [[[abc2003]]] Gall Anonim. 'An article', Whatever. 2003.

[glossary]
Example Glossary
----------------
Glossaries are optional. Glossaries entries are an example of a style
of AsciiDoc labeled lists.

[glossary]
A glossary term::
The corresponding (indented) definition.

A second glossary term::
The corresponding (indented) definition.


[colophon]
Example Colophon
----------------
Text at the end of a book describing facts about its production.
////


[index]
Index
-----
////////////////////////////////////////////////////////////////
The index is normally left completely empty, it's contents being
generated automatically by the DocBook toolchain.
////////////////////////////////////////////////////////////////
