//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using org.uddi.apiv3;
using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.17929.
// 
namespace org.apache.juddi.apiv3
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "JUDDIApiServiceSoapBinding", Namespace = "urn:juddi-apache-org:v3_service")]
    public partial class JUDDIApiService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback get_publisherDetailOperationCompleted;

        private System.Threading.SendOrPostCallback delete_ClientSubscriptionInfoOperationCompleted;

        private System.Threading.SendOrPostCallback save_ClerkOperationCompleted;

        private System.Threading.SendOrPostCallback get_allPublisherDetailOperationCompleted;

        private System.Threading.SendOrPostCallback delete_publisherOperationCompleted;

        private System.Threading.SendOrPostCallback save_publisherOperationCompleted;

        private System.Threading.SendOrPostCallback save_NodeOperationCompleted;

        private System.Threading.SendOrPostCallback adminDelete_tmodelOperationCompleted;

        private System.Threading.SendOrPostCallback save_ClientSubscriptionInfoOperationCompleted;

        private System.Threading.SendOrPostCallback invoke_SyncSubscriptionOperationCompleted;

        /// <remarks/>
        public JUDDIApiService()
        {
            this.Url = "http://uddi-jbossoverlord.rhcloud.com/services/juddi-api";
        }

        /// <remarks/>
        public event get_publisherDetailCompletedEventHandler get_publisherDetailCompleted;

        /// <remarks/>
        public event delete_ClientSubscriptionInfoCompletedEventHandler delete_ClientSubscriptionInfoCompleted;

        /// <remarks/>
        public event save_ClerkCompletedEventHandler save_ClerkCompleted;

        /// <remarks/>
        public event get_allPublisherDetailCompletedEventHandler get_allPublisherDetailCompleted;

        /// <remarks/>
        public event delete_publisherCompletedEventHandler delete_publisherCompleted;

        /// <remarks/>
        public event save_publisherCompletedEventHandler save_publisherCompleted;

        /// <remarks/>
        public event save_NodeCompletedEventHandler save_NodeCompleted;

        /// <remarks/>
        public event adminDelete_tmodelCompletedEventHandler adminDelete_tmodelCompleted;

        /// <remarks/>
        public event save_ClientSubscriptionInfoCompletedEventHandler save_ClientSubscriptionInfoCompleted;

        /// <remarks/>
        public event invoke_SyncSubscriptionCompletedEventHandler invoke_SyncSubscriptionCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("get_publisherDetail", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("publisherDetail", Namespace = "urn:juddi-apache-org:api_v3")]
        public publisherDetail get_publisherDetail([System.Xml.Serialization.XmlElementAttribute("get_publisherDetail", Namespace = "urn:juddi-apache-org:api_v3")] get_publisher_detail get_publisherDetail1)
        {
            object[] results = this.Invoke("get_publisherDetail", new object[] {
						get_publisherDetail1});
            return ((publisherDetail)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult Beginget_publisherDetail(get_publisher_detail get_publisherDetail1, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("get_publisherDetail", new object[] {
						get_publisherDetail1}, callback, asyncState);
        }

        /// <remarks/>
        public publisherDetail Endget_publisherDetail(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((publisherDetail)(results[0]));
        }

        /// <remarks/>
        public void get_publisherDetailAsync(get_publisher_detail get_publisherDetail1)
        {
            this.get_publisherDetailAsync(get_publisherDetail1, null);
        }

        /// <remarks/>
        public void get_publisherDetailAsync(get_publisher_detail get_publisherDetail1, object userState)
        {
            if ((this.get_publisherDetailOperationCompleted == null))
            {
                this.get_publisherDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_publisherDetailOperationCompleted);
            }
            this.InvokeAsync("get_publisherDetail", new object[] {
						get_publisherDetail1}, this.get_publisherDetailOperationCompleted, userState);
        }

        private void Onget_publisherDetailOperationCompleted(object arg)
        {
            if ((this.get_publisherDetailCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_publisherDetailCompleted(this, new get_publisherDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("delete_ClientSubscriptionInfo", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void delete_ClientSubscriptionInfo([System.Xml.Serialization.XmlElementAttribute("delete_ClientSubscriptionInfo", Namespace = "urn:juddi-apache-org:api_v3", IsNullable = true)] delete_clientSubscriptionInfo delete_ClientSubscriptionInfo1)
        {
            this.Invoke("delete_ClientSubscriptionInfo", new object[] {
						delete_ClientSubscriptionInfo1});
        }

        /// <remarks/>
        public System.IAsyncResult Begindelete_ClientSubscriptionInfo(delete_clientSubscriptionInfo delete_ClientSubscriptionInfo1, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("delete_ClientSubscriptionInfo", new object[] {
						delete_ClientSubscriptionInfo1}, callback, asyncState);
        }

        /// <remarks/>
        public void Enddelete_ClientSubscriptionInfo(System.IAsyncResult asyncResult)
        {
            this.EndInvoke(asyncResult);
        }

        /// <remarks/>
        public void delete_ClientSubscriptionInfoAsync(delete_clientSubscriptionInfo delete_ClientSubscriptionInfo1)
        {
            this.delete_ClientSubscriptionInfoAsync(delete_ClientSubscriptionInfo1, null);
        }

        /// <remarks/>
        public void delete_ClientSubscriptionInfoAsync(delete_clientSubscriptionInfo delete_ClientSubscriptionInfo1, object userState)
        {
            if ((this.delete_ClientSubscriptionInfoOperationCompleted == null))
            {
                this.delete_ClientSubscriptionInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.Ondelete_ClientSubscriptionInfoOperationCompleted);
            }
            this.InvokeAsync("delete_ClientSubscriptionInfo", new object[] {
						delete_ClientSubscriptionInfo1}, this.delete_ClientSubscriptionInfoOperationCompleted, userState);
        }

        private void Ondelete_ClientSubscriptionInfoOperationCompleted(object arg)
        {
            if ((this.delete_ClientSubscriptionInfoCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.delete_ClientSubscriptionInfoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("save_Clerk", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("save_ClerkResponse", Namespace = "urn:juddi-apache-org:v3_service", IsNullable = true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace = "urn:juddi-apache-org:api_v3")]
        public clerk[] save_Clerk([System.Xml.Serialization.XmlElementAttribute("save_Clerk", Namespace = "urn:juddi-apache-org:api_v3", IsNullable = true)] save_clerkInfo save_Clerk1)
        {
            object[] results = this.Invoke("save_Clerk", new object[] {
						save_Clerk1});
            return ((clerk[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult Beginsave_Clerk(save_clerkInfo save_Clerk1, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("save_Clerk", new object[] {
						save_Clerk1}, callback, asyncState);
        }

        /// <remarks/>
        public clerk[] Endsave_Clerk(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((clerk[])(results[0]));
        }

        /// <remarks/>
        public void save_ClerkAsync(save_clerkInfo save_Clerk1)
        {
            this.save_ClerkAsync(save_Clerk1, null);
        }

        /// <remarks/>
        public void save_ClerkAsync(save_clerkInfo save_Clerk1, object userState)
        {
            if ((this.save_ClerkOperationCompleted == null))
            {
                this.save_ClerkOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsave_ClerkOperationCompleted);
            }
            this.InvokeAsync("save_Clerk", new object[] {
						save_Clerk1}, this.save_ClerkOperationCompleted, userState);
        }

        private void Onsave_ClerkOperationCompleted(object arg)
        {
            if ((this.save_ClerkCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.save_ClerkCompleted(this, new save_ClerkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("get_allPublisherDetail", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("publisherDetail", Namespace = "urn:juddi-apache-org:api_v3")]
        public publisherDetail get_allPublisherDetail([System.Xml.Serialization.XmlElementAttribute("get_allPublisherDetail", Namespace = "urn:juddi-apache-org:api_v3")] get_allPublisherDetail get_allPublisherDetail1)
        {
            object[] results = this.Invoke("get_allPublisherDetail", new object[] {
						get_allPublisherDetail1});
            return ((publisherDetail)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult Beginget_allPublisherDetail(get_allPublisherDetail get_allPublisherDetail1, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("get_allPublisherDetail", new object[] {
						get_allPublisherDetail1}, callback, asyncState);
        }

        /// <remarks/>
        public publisherDetail Endget_allPublisherDetail(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((publisherDetail)(results[0]));
        }

        /// <remarks/>
        public void get_allPublisherDetailAsync(get_allPublisherDetail get_allPublisherDetail1)
        {
            this.get_allPublisherDetailAsync(get_allPublisherDetail1, null);
        }

        /// <remarks/>
        public void get_allPublisherDetailAsync(get_allPublisherDetail get_allPublisherDetail1, object userState)
        {
            if ((this.get_allPublisherDetailOperationCompleted == null))
            {
                this.get_allPublisherDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.Onget_allPublisherDetailOperationCompleted);
            }
            this.InvokeAsync("get_allPublisherDetail", new object[] {
						get_allPublisherDetail1}, this.get_allPublisherDetailOperationCompleted, userState);
        }

        private void Onget_allPublisherDetailOperationCompleted(object arg)
        {
            if ((this.get_allPublisherDetailCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.get_allPublisherDetailCompleted(this, new get_allPublisherDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("delete_publisher", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void delete_publisher([System.Xml.Serialization.XmlElementAttribute("delete_publisher", Namespace = "urn:juddi-apache-org:api_v3")] delete_publisher delete_publisher1)
        {
            this.Invoke("delete_publisher", new object[] {
						delete_publisher1});
        }

        /// <remarks/>
        public System.IAsyncResult Begindelete_publisher(delete_publisher delete_publisher1, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("delete_publisher", new object[] {
						delete_publisher1}, callback, asyncState);
        }

        /// <remarks/>
        public void Enddelete_publisher(System.IAsyncResult asyncResult)
        {
            this.EndInvoke(asyncResult);
        }

        /// <remarks/>
        public void delete_publisherAsync(delete_publisher delete_publisher1)
        {
            this.delete_publisherAsync(delete_publisher1, null);
        }

        /// <remarks/>
        public void delete_publisherAsync(delete_publisher delete_publisher1, object userState)
        {
            if ((this.delete_publisherOperationCompleted == null))
            {
                this.delete_publisherOperationCompleted = new System.Threading.SendOrPostCallback(this.Ondelete_publisherOperationCompleted);
            }
            this.InvokeAsync("delete_publisher", new object[] {
						delete_publisher1}, this.delete_publisherOperationCompleted, userState);
        }

        private void Ondelete_publisherOperationCompleted(object arg)
        {
            if ((this.delete_publisherCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.delete_publisherCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("save_publisher", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("save_publisherResponse", Namespace = "urn:juddi-apache-org:v3_service", IsNullable = true)]
        public publisherDetail save_publisher([System.Xml.Serialization.XmlElementAttribute("save_publisher", Namespace = "urn:juddi-apache-org:api_v3")] save_publisher save_publisher1)
        {
            object[] results = this.Invoke("save_publisher", new object[] {
						save_publisher1});
            return ((publisherDetail)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult Beginsave_publisher(save_publisher save_publisher1, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("save_publisher", new object[] {
						save_publisher1}, callback, asyncState);
        }

        /// <remarks/>
        public publisherDetail Endsave_publisher(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((publisherDetail)(results[0]));
        }

        /// <remarks/>
        public void save_publisherAsync(save_publisher save_publisher1)
        {
            this.save_publisherAsync(save_publisher1, null);
        }

        /// <remarks/>
        public void save_publisherAsync(save_publisher save_publisher1, object userState)
        {
            if ((this.save_publisherOperationCompleted == null))
            {
                this.save_publisherOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsave_publisherOperationCompleted);
            }
            this.InvokeAsync("save_publisher", new object[] {
						save_publisher1}, this.save_publisherOperationCompleted, userState);
        }

        private void Onsave_publisherOperationCompleted(object arg)
        {
            if ((this.save_publisherCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.save_publisherCompleted(this, new save_publisherCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("save_Node", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("save_NodeResponse", Namespace = "urn:juddi-apache-org:v3_service", IsNullable = true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace = "urn:juddi-apache-org:api_v3")]
        public node[] save_Node([System.Xml.Serialization.XmlElementAttribute("save_Node", Namespace = "urn:juddi-apache-org:api_v3", IsNullable = true)] save_nodeInfo save_Node1)
        {
            object[] results = this.Invoke("save_Node", new object[] {
						save_Node1});
            return ((node[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult Beginsave_Node(save_nodeInfo save_Node1, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("save_Node", new object[] {
						save_Node1}, callback, asyncState);
        }

        /// <remarks/>
        public node[] Endsave_Node(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((node[])(results[0]));
        }

        /// <remarks/>
        public void save_NodeAsync(save_nodeInfo save_Node1)
        {
            this.save_NodeAsync(save_Node1, null);
        }

        /// <remarks/>
        public void save_NodeAsync(save_nodeInfo save_Node1, object userState)
        {
            if ((this.save_NodeOperationCompleted == null))
            {
                this.save_NodeOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsave_NodeOperationCompleted);
            }
            this.InvokeAsync("save_Node", new object[] {
						save_Node1}, this.save_NodeOperationCompleted, userState);
        }

        private void Onsave_NodeOperationCompleted(object arg)
        {
            if ((this.save_NodeCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.save_NodeCompleted(this, new save_NodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("adminDelete_tmodel", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void adminDelete_tmodel([System.Xml.Serialization.XmlElementAttribute("adminDelete_tmodel", Namespace = "urn:juddi-apache-org:api_v3", IsNullable = true)] delete_tModel adminDelete_tmodel1)
        {
            this.Invoke("adminDelete_tmodel", new object[] {
						adminDelete_tmodel1});
        }

        /// <remarks/>
        public System.IAsyncResult BeginadminDelete_tmodel(delete_tModel adminDelete_tmodel1, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("adminDelete_tmodel", new object[] {
						adminDelete_tmodel1}, callback, asyncState);
        }

        /// <remarks/>
        public void EndadminDelete_tmodel(System.IAsyncResult asyncResult)
        {
            this.EndInvoke(asyncResult);
        }

        /// <remarks/>
        public void adminDelete_tmodelAsync(delete_tModel adminDelete_tmodel1)
        {
            this.adminDelete_tmodelAsync(adminDelete_tmodel1, null);
        }

        /// <remarks/>
        public void adminDelete_tmodelAsync(delete_tModel adminDelete_tmodel1, object userState)
        {
            if ((this.adminDelete_tmodelOperationCompleted == null))
            {
                this.adminDelete_tmodelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnadminDelete_tmodelOperationCompleted);
            }
            this.InvokeAsync("adminDelete_tmodel", new object[] {
						adminDelete_tmodel1}, this.adminDelete_tmodelOperationCompleted, userState);
        }

        private void OnadminDelete_tmodelOperationCompleted(object arg)
        {
            if ((this.adminDelete_tmodelCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.adminDelete_tmodelCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("save_ClientSubscriptionInfo", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("save_ClientSubscriptionInfoResponse", Namespace = "urn:juddi-apache-org:v3_service", IsNullable = true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace = "urn:juddi-apache-org:api_v3")]
        public clientSubscriptionInfo[] save_ClientSubscriptionInfo([System.Xml.Serialization.XmlElementAttribute("save_ClientSubscriptionInfo", Namespace = "urn:juddi-apache-org:api_v3", IsNullable = true)] save_clientSubscriptionInfo save_ClientSubscriptionInfo1)
        {
            object[] results = this.Invoke("save_ClientSubscriptionInfo", new object[] {
						save_ClientSubscriptionInfo1});
            return ((clientSubscriptionInfo[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult Beginsave_ClientSubscriptionInfo(save_clientSubscriptionInfo save_ClientSubscriptionInfo1, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("save_ClientSubscriptionInfo", new object[] {
						save_ClientSubscriptionInfo1}, callback, asyncState);
        }

        /// <remarks/>
        public clientSubscriptionInfo[] Endsave_ClientSubscriptionInfo(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((clientSubscriptionInfo[])(results[0]));
        }

        /// <remarks/>
        public void save_ClientSubscriptionInfoAsync(save_clientSubscriptionInfo save_ClientSubscriptionInfo1)
        {
            this.save_ClientSubscriptionInfoAsync(save_ClientSubscriptionInfo1, null);
        }

        /// <remarks/>
        public void save_ClientSubscriptionInfoAsync(save_clientSubscriptionInfo save_ClientSubscriptionInfo1, object userState)
        {
            if ((this.save_ClientSubscriptionInfoOperationCompleted == null))
            {
                this.save_ClientSubscriptionInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsave_ClientSubscriptionInfoOperationCompleted);
            }
            this.InvokeAsync("save_ClientSubscriptionInfo", new object[] {
						save_ClientSubscriptionInfo1}, this.save_ClientSubscriptionInfoOperationCompleted, userState);
        }

        private void Onsave_ClientSubscriptionInfoOperationCompleted(object arg)
        {
            if ((this.save_ClientSubscriptionInfoCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.save_ClientSubscriptionInfoCompleted(this, new save_ClientSubscriptionInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("invoke_SyncSubscription", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("invoke_SyncSubscriptionResponse", Namespace = "urn:juddi-apache-org:v3_service", IsNullable = true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("list", Namespace = "urn:juddi-apache-org:api_v3")]
        public subscriptionResultsList[] invoke_SyncSubscription([System.Xml.Serialization.XmlElementAttribute("invoke_SyncSubscription", Namespace = "urn:juddi-apache-org:api_v3", IsNullable = true)] syncSubscription invoke_SyncSubscription1)
        {
            object[] results = this.Invoke("invoke_SyncSubscription", new object[] {
						invoke_SyncSubscription1});
            return ((subscriptionResultsList[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult Begininvoke_SyncSubscription(syncSubscription invoke_SyncSubscription1, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("invoke_SyncSubscription", new object[] {
						invoke_SyncSubscription1}, callback, asyncState);
        }

        /// <remarks/>
        public subscriptionResultsList[] Endinvoke_SyncSubscription(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((subscriptionResultsList[])(results[0]));
        }

        /// <remarks/>
        public void invoke_SyncSubscriptionAsync(syncSubscription invoke_SyncSubscription1)
        {
            this.invoke_SyncSubscriptionAsync(invoke_SyncSubscription1, null);
        }

        /// <remarks/>
        public void invoke_SyncSubscriptionAsync(syncSubscription invoke_SyncSubscription1, object userState)
        {
            if ((this.invoke_SyncSubscriptionOperationCompleted == null))
            {
                this.invoke_SyncSubscriptionOperationCompleted = new System.Threading.SendOrPostCallback(this.Oninvoke_SyncSubscriptionOperationCompleted);
            }
            this.InvokeAsync("invoke_SyncSubscription", new object[] {
						invoke_SyncSubscription1}, this.invoke_SyncSubscriptionOperationCompleted, userState);
        }

        private void Oninvoke_SyncSubscriptionOperationCompleted(object arg)
        {
            if ((this.invoke_SyncSubscriptionCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.invoke_SyncSubscriptionCompleted(this, new invoke_SyncSubscriptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:juddi-apache-org:api_v3")]
    public partial class get_publisher_detail
    {

        private string authInfoField;

        private string[] publisherIdField;
        [System.Xml.Serialization.XmlElement(Namespace = "urn:uddi-org:api_v3")]
        /// <remarks/>
        public string authInfo
        {
            get
            {
                return this.authInfoField;
            }
            set
            {
                this.authInfoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("publisherId")]
        public string[] publisherId
        {
            get
            {
                return this.publisherIdField;
            }
            set
            {
                this.publisherIdField = value;
            }
        }
    }




    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:juddi-apache-org:api_v3")]
    public partial class syncSubscription
    {

        private string authInfoField;

        private get_subscriptionResults[] listField;
        [System.Xml.Serialization.XmlElement(Namespace = "urn:uddi-org:api_v3")]
        
        public string authInfo
        {
            get
            {
                return this.authInfoField;
            }
            set
            {
                this.authInfoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("list", IsNullable = true)]
        public get_subscriptionResults[] list
        {
            get
            {
                return this.listField;
            }
            set
            {
                this.listField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:juddi-apache-org:api_v3")]
    public partial class clientSubscriptionInfo
    {

        private string subscriptionKeyField;

        private clerk fromClerkField;

        private clerk toClerkField;

        private System.DateTime lastModifiedField;

        private bool lastModifiedFieldSpecified;

        /// <remarks/>
        public string subscriptionKey
        {
            get
            {
                return this.subscriptionKeyField;
            }
            set
            {
                this.subscriptionKeyField = value;
            }
        }

        /// <remarks/>
        public clerk fromClerk
        {
            get
            {
                return this.fromClerkField;
            }
            set
            {
                this.fromClerkField = value;
            }
        }

        /// <remarks/>
        public clerk toClerk
        {
            get
            {
                return this.toClerkField;
            }
            set
            {
                this.toClerkField = value;
            }
        }

        /// <remarks/>
        public System.DateTime lastModified
        {
            get
            {
                return this.lastModifiedField;
            }
            set
            {
                this.lastModifiedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastModifiedSpecified
        {
            get
            {
                return this.lastModifiedFieldSpecified;
            }
            set
            {
                this.lastModifiedFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:juddi-apache-org:api_v3")]
    public partial class clerk
    {

        private string nameField;

        private node nodeField;

        private string publisherField;

        private string passwordField;

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public node node
        {
            get
            {
                return this.nodeField;
            }
            set
            {
                this.nodeField = value;
            }
        }

        /// <remarks/>
        public string publisher
        {
            get
            {
                return this.publisherField;
            }
            set
            {
                this.publisherField = value;
            }
        }

        /// <remarks/>
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:juddi-apache-org:api_v3")]
    public partial class node
    {

        private string nameField;

        private string clientNameField;

        private string descriptionField;

        private string custodyTransferUrlField;

        private string inquiryUrlField;

        private string publishUrlField;

        private string securityUrlField;

        private string subscriptionUrlField;

        private string subscriptionListenerUrlField;
		
		private string replicationUrlField;

        private string juddiApiUrlField;

        private string proxyTransportField;

        private string factoryInitialField;

        private string factoryURLPkgsField;

        private string factoryNamingProviderField;

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string clientName
        {
            get
            {
                return this.clientNameField;
            }
            set
            {
                this.clientNameField = value;
            }
        }

        /// <remarks/>
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string custodyTransferUrl
        {
            get
            {
                return this.custodyTransferUrlField;
            }
            set
            {
                this.custodyTransferUrlField = value;
            }
        }

        /// <remarks/>
        public string inquiryUrl
        {
            get
            {
                return this.inquiryUrlField;
            }
            set
            {
                this.inquiryUrlField = value;
            }
        }

        /// <remarks/>
        public string publishUrl
        {
            get
            {
                return this.publishUrlField;
            }
            set
            {
                this.publishUrlField = value;
            }
        }

        /// <remarks/>
        public string securityUrl
        {
            get
            {
                return this.securityUrlField;
            }
            set
            {
                this.securityUrlField = value;
            }
        }

        /// <remarks/>
        public string subscriptionUrl
        {
            get
            {
                return this.subscriptionUrlField;
            }
            set
            {
                this.subscriptionUrlField = value;
            }
        }

        /// <remarks/>
        public string subscriptionListenerUrl
        {
            get
            {
                return this.subscriptionListenerUrlField;
            }
            set
            {
                this.subscriptionListenerUrlField = value;
            }
        }

		/// <remarks/>
		public string replicationUrl {
			get {
				return this.replicationUrlField;
			}
			set {
				this.replicationUrlField = value;
			}
		}

        /// <remarks/>
        public string juddiApiUrl
        {
            get
            {
                return this.juddiApiUrlField;
            }
            set
            {
                this.juddiApiUrlField = value;
            }
        }

        /// <remarks/>
        public string proxyTransport
        {
            get
            {
                return this.proxyTransportField;
            }
            set
            {
                this.proxyTransportField = value;
            }
        }

        /// <remarks/>
        public string factoryInitial
        {
            get
            {
                return this.factoryInitialField;
            }
            set
            {
                this.factoryInitialField = value;
            }
        }

        /// <remarks/>
        public string factoryURLPkgs
        {
            get
            {
                return this.factoryURLPkgsField;
            }
            set
            {
                this.factoryURLPkgsField = value;
            }
        }

        /// <remarks/>
        public string factoryNamingProvider
        {
            get
            {
                return this.factoryNamingProviderField;
            }
            set
            {
                this.factoryNamingProviderField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:juddi-apache-org:api_v3")]
    public partial class save_clientSubscriptionInfo
    {

        private string authInfoField;

        private clientSubscriptionInfo[] clientSubscriptionInfoField;
        [System.Xml.Serialization.XmlElement(Namespace = "urn:uddi-org:api_v3")]
        /// <remarks/>
        public string authInfo
        {
            get
            {
                return this.authInfoField;
            }
            set
            {
                this.authInfoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("clientSubscriptionInfo")]
        public clientSubscriptionInfo[] clientSubscriptionInfo
        {
            get
            {
                return this.clientSubscriptionInfoField;
            }
            set
            {
                this.clientSubscriptionInfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:uddi-org:api_v3")]
    public partial class delete_tModel
    {

        private string authInfoField;

        private string[] tModelKeyField;
        [System.Xml.Serialization.XmlElement(Namespace = "urn:uddi-org:api_v3")]
        /// <remarks/>
        public string authInfo
        {
            get
            {
                return this.authInfoField;
            }
            set
            {
                this.authInfoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tModelKey")]
        public string[] tModelKey
        {
            get
            {
                return this.tModelKeyField;
            }
            set
            {
                this.tModelKeyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:juddi-apache-org:api_v3")]
    public partial class save_nodeInfo
    {

        private string authInfoField;

        private node[] nodeField;

        /// <remarks/>
        /// 
        [System.Xml.Serialization.XmlElement(Namespace = "urn:uddi-org:api_v3")]
        public string authInfo
        {
            get
            {
                return this.authInfoField;
            }
            set
            {
                this.authInfoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("node")]
        public node[] node
        {
            get
            {
                return this.nodeField;
            }
            set
            {
                this.nodeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:juddi-apache-org:api_v3")]
    public partial class save_publisher
    {

        private string authInfoField;

        private publisher[] publisherField;

        [System.Xml.Serialization.XmlElement(Namespace = "urn:uddi-org:api_v3")]
        public string authInfo
        {
            get
            {
                return this.authInfoField;
            }
            set
            {
                this.authInfoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("publisher")]
        public publisher[] publisher
        {
            get
            {
                return this.publisherField;
            }
            set
            {
                this.publisherField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:juddi-apache-org:api_v3")]
    public partial class publisher
    {

        private string publisherNameField;

        private string emailAddressField;

        private string isAdminField;

        private string isEnabledField;

        private int maxBindingsPerServiceField;

        private bool maxBindingsPerServiceFieldSpecified;

        private int maxBusinessesField;

        private bool maxBusinessesFieldSpecified;

        private int maxServicePerBusinessField;

        private bool maxServicePerBusinessFieldSpecified;

        private int maxTModelsField;

        private bool maxTModelsFieldSpecified;

        private SignatureType[] signatureField;

        private string authorizedNameField;

        /// <remarks/>
        public string publisherName
        {
            get
            {
                return this.publisherNameField;
            }
            set
            {
                this.publisherNameField = value;
            }
        }

        /// <remarks/>
        public string emailAddress
        {
            get
            {
                return this.emailAddressField;
            }
            set
            {
                this.emailAddressField = value;
            }
        }

        /// <remarks/>
        public string isAdmin
        {
            get
            {
                return this.isAdminField;
            }
            set
            {
                this.isAdminField = value;
            }
        }

        /// <remarks/>
        public string isEnabled
        {
            get
            {
                return this.isEnabledField;
            }
            set
            {
                this.isEnabledField = value;
            }
        }

        /// <remarks/>
        public int maxBindingsPerService
        {
            get
            {
                return this.maxBindingsPerServiceField;
            }
            set
            {
                this.maxBindingsPerServiceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxBindingsPerServiceSpecified
        {
            get
            {
                return this.maxBindingsPerServiceFieldSpecified;
            }
            set
            {
                this.maxBindingsPerServiceFieldSpecified = value;
            }
        }

        /// <remarks/>
        public int maxBusinesses
        {
            get
            {
                return this.maxBusinessesField;
            }
            set
            {
                this.maxBusinessesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxBusinessesSpecified
        {
            get
            {
                return this.maxBusinessesFieldSpecified;
            }
            set
            {
                this.maxBusinessesFieldSpecified = value;
            }
        }

        /// <remarks/>
        public int maxServicePerBusiness
        {
            get
            {
                return this.maxServicePerBusinessField;
            }
            set
            {
                this.maxServicePerBusinessField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxServicePerBusinessSpecified
        {
            get
            {
                return this.maxServicePerBusinessFieldSpecified;
            }
            set
            {
                this.maxServicePerBusinessFieldSpecified = value;
            }
        }

        /// <remarks/>
        public int maxTModels
        {
            get
            {
                return this.maxTModelsField;
            }
            set
            {
                this.maxTModelsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxTModelsSpecified
        {
            get
            {
                return this.maxTModelsFieldSpecified;
            }
            set
            {
                this.maxTModelsFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Signature", Namespace = "http://www.w3.org/2000/09/xmldsig#")]
        public SignatureType[] Signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string authorizedName
        {
            get
            {
                return this.authorizedNameField;
            }
            set
            {
                this.authorizedNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:juddi-apache-org:api_v3")]
    public partial class delete_publisher
    {

        private string authInfoField;

        private string[] publisherIdField;

        [System.Xml.Serialization.XmlElement(Namespace = "urn:uddi-org:api_v3")]
        public string authInfo
        {
            get
            {
                return this.authInfoField;
            }
            set
            {
                this.authInfoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("publisherId")]
        public string[] publisherId
        {
            get
            {
                return this.publisherIdField;
            }
            set
            {
                this.publisherIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:juddi-apache-org:api_v3")]
    public partial class get_allPublisherDetail
    {

        private string authInfoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:uddi-org:api_v3")]
        public string authInfo
        {
            get
            {
                return this.authInfoField;
            }
            set
            {
                this.authInfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:juddi-apache-org:api_v3")]
    public partial class save_clerkInfo
    {

        private string authInfoField;

        private clerk[] clerkField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElement(Namespace = "urn:uddi-org:api_v3")]
        public string authInfo
        {
            get
            {
                return this.authInfoField;
            }
            set
            {
                this.authInfoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("clerk")]
        public clerk[] clerk
        {
            get
            {
                return this.clerkField;
            }
            set
            {
                this.clerkField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:juddi-apache-org:api_v3")]
    public partial class delete_clientSubscriptionInfo
    {

        private string authInfoField;

        private string[] subscriptionKeyField;

        /// <remarks/>
        /// 
        [System.Xml.Serialization.XmlElement(Namespace = "urn:uddi-org:api_v3")]
        public string authInfo
        {
            get
            {
                return this.authInfoField;
            }
            set
            {
                this.authInfoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("subscriptionKey")]
        public string[] subscriptionKey
        {
            get
            {
                return this.subscriptionKeyField;
            }
            set
            {
                this.subscriptionKeyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:juddi-apache-org:api_v3")]
    public partial class publisherDetail
    {

        private publisher[] publisherField;

        private bool truncatedField;

        private bool truncatedFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("publisher", IsNullable = true)]
        public publisher[] publisher
        {
            get
            {
                return this.publisherField;
            }
            set
            {
                this.publisherField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool truncated
        {
            get
            {
                return this.truncatedField;
            }
            set
            {
                this.truncatedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool truncatedSpecified
        {
            get
            {
                return this.truncatedFieldSpecified;
            }
            set
            {
                this.truncatedFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void get_publisherDetailCompletedEventHandler(object sender, get_publisherDetailCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_publisherDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal get_publisherDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public publisherDetail Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((publisherDetail)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void delete_ClientSubscriptionInfoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void save_ClerkCompletedEventHandler(object sender, save_ClerkCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class save_ClerkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal save_ClerkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public clerk[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((clerk[])(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void get_allPublisherDetailCompletedEventHandler(object sender, get_allPublisherDetailCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class get_allPublisherDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal get_allPublisherDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public publisherDetail Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((publisherDetail)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void delete_publisherCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void save_publisherCompletedEventHandler(object sender, save_publisherCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class save_publisherCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal save_publisherCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public publisherDetail Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((publisherDetail)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void save_NodeCompletedEventHandler(object sender, save_NodeCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class save_NodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal save_NodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public node[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((node[])(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void adminDelete_tmodelCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void save_ClientSubscriptionInfoCompletedEventHandler(object sender, save_ClientSubscriptionInfoCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class save_ClientSubscriptionInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal save_ClientSubscriptionInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public clientSubscriptionInfo[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((clientSubscriptionInfo[])(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void invoke_SyncSubscriptionCompletedEventHandler(object sender, invoke_SyncSubscriptionCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class invoke_SyncSubscriptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal invoke_SyncSubscriptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public subscriptionResultsList[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((subscriptionResultsList[])(this.results[0]));
            }
        }
    }
}