USE juddi;

-- *** SAMPLE PUBLISHER ***
-- INSERT INTO PUBLISHER (PUBLISHER_ID,PUBLISHER_NAME,EMAIL_ADDRESS,IS_ENABLED,IS_ADMIN)
-- VALUES ('jdoe','John Doe','john.doe@apache.org','true','true',25,20,10,100);

